### ISSUE TITLE
db variable in server.js making server crash

### ISSUE THREAD

**Issue by OrianP** [fac-23/week3-auth-team2#32]
Hi Milly, 

I think we are not using the db variable in any other files except for model.js and newsfeed.js at the moment. 
When I pulled form main my local server was crashing. I commented out the db variable from server.js and now it works (after I made the change from the other issue - changed the `connection.js` file path in `model.js` to `./connection.js` instead of two dots. 

https://github.com/fac-23/week3-auth-team2/blob/8ba8bde3de9a4bda5266a33bd6177252a143ae9e/server.js#L3

**Comment by miahbates** [comment]
done
