### ISSUE TITLE
Always handle promise rejections in your routes

### ISSUE THREAD

**Issue by oliverjam** [fac-23/week3-auth-team2#34]
Your `/newsfeed` route doesn't have a `.catch` on the promise returned by `model.addItem`. This means if something goes wrong inside that function (which is likely since it's quite complex), your server just crashes and the user gets a completely broken page. On Heroku this would also take down your server and prevent _any_ users from getting responses on _any_ pages (until Heroku managed to restart the server).

In this case I can quite easily trigger a crash by entering a random username into the add item form (since looking up the nonexistent user id fails and causes the promise to reject).

You must always attach a `.catch` to any promises in your route handlers. That way you can always send a response to the user and stop the server crashing. It can be as basic as:

```js
model.addItem(...stuff)
  .then(() => {
    redirect("/newsfeed");
  })
  .catch(error => {
    console.error(error);
    res.send(`<h1>Something went wrong</h1>`)
  })
```

although obviously more granular error-handling that tells the user how to retry etc would be nice :)

**Comment by miahbates** [comment]
fixed

**Comment by oliverjam** [comment]
Don't forgot to link the commit/PR to the issue, so you can see where it was fixed! E.g. I can't see a commit that makes this change yet
