### ISSUE TITLE
db variable

### ISSUE THREAD

**Issue by danilo-cupido** [fac-23/week3-auth-team2#36]
in `connection.js`, line 13 you should have `ssl: false` otherwise the local server will keep crashing: 
`Error: The server does not support SSL connections`

<img width="372" alt="Screenshot 2022-01-28 at 10 24 51" src="https://user-images.githubusercontent.com/81513148/151530830-5fe4f366-1d5b-4056-992a-1f48ac84e230.png">

**Comment by danilo-cupido** [comment]
Just `ssl: false`, NOT `ssl: rejectUnauthorized: false`

**Comment by miahbates** [comment]
done :spakles:
